name: Deploy

on:
  push:
    branches:
      - master
      - staging

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install additional dependencies
        run: npm install mysql2 promise
      - name: deploy
        run: |
          npx ncc build src/index.js
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name wordworm-lambda --zip-file fileb://deploy.zip
        
