name: Deploy

on:
  push:
    branches:
      - master
      - staging

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          npx ncc build src/index.js
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=wordworm-lambda --zip-file=fileb://deploy.zip
